### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by mixophrygian** [JedWatson/generator-react-express#1]
Heads up, out of the box `node server` fails, citing the inability to find reactify.  Went ahead and `npm install --save reactify` only to get the following error: 

`transform: [babelify.configure({`

`ReferenceError: babelify is not defined`

But it turns out `npm install`ing and `--save`ing babelify resolves the issue. (As well as importing babelify to server.js)

**Comment by JedWatson** [comment]
Sounds like something's all out of whack, I'll take a look.

**Comment by JedWatson** [comment]
Hi @mixophrygian, I've fixed that issue and just published a new version - v0.2.2

Thanks for the report!

**Comment by mixophrygian** [comment]
:+1:
